name: Run Vite Automation Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run my custom script
      run: npx cypress run --spec "cypress/e2e/front-end.cy.js"