name: Run Vite Automation Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # adjust to your project version

    - name: Install dependencies
      run: npm install

    - name: Install Cypress binary
      run: npx cypress install
    
    - name: Start the server for frontend testing
      run: |
        node server.js &
        BACKEND_PID=$!
        npx wait-on http://localhost:3100

    - name: To start on local machine
      run: |
        npm run start &
        FRONTEND_PID=$!
        npx wait-on http://localhost:3001  

    - name: Run my custom script
      run: npm run cypress:run:headless

    - name: Clean up background servers
      if: always()
      run: |
        kill $BACKEND_PID || true
        kill $FRONTEND_PID || true
